n    % Promptbuilder Constructs LLM Prompts for Each BPMN Data Generation Stage
nnn            % Embed Table and Relationship Metadata Into A prompt
n                'You are given the following database scheme: \n%s \n', ...
                'Generates Json Rows that Strictly adhere to thesis Tables and Foreign-Key Constraints.'
nnnn            % ASK llm to break a product description into BPMN phases
n                'Given the product:"%s", List Major BPMN Stages (e.G. RAW Material Prep, Subassembly, Testing, Packaging)', ...
                'as an ordered JSON array with names and short descriptions.'
nnnn            % Generates Tasks/Gateways/Events for A Specific Phase
n                'Phase: %s %s \n', ...
                'Context IDS: %s \n', ...
                'Generates %D JSON ROWS for BPMN ENTITIES (tasks, gateways, events) with these columns.'
nnnn            % Define Sequence and Conditional Flows Linking Phasees
n                'With thesis phase entity ids: %s \n', ...
                'Generates BPMN sequenceFlow and MessageFlow Json Objects that Connect Them into a Coherent Process.'
nnnn            % Assign Bins, Roles, and Tools to Tasks
n                'Given tasks: %s and resources scheme: %s \n', ...
                'Generates JSON ROWS for Resource Assignments (Bins, Tools, Performers).'  
nnnn            % Validate Referential Integrity Before Export
n                'Full bpmn context: %s \n', ...
                'List Any Missing Links, Orphan Elements, or FK Violations.Return Empty List if all good.'
nnnn            % Produce Final BPMN-XML or Combined Json Diagram
n                'Final BPMN Context: %s \n', ...
                'Output a single valid bpmn-xml snippet enCassing tasks, events, gateways, and flows.'
nnnn            % Generic Prompt for Table Specific Row Generation
n                'Generates %d rows for table"%s"with scheme %s and context ids %s.'
nnnn